version: "3.4"

services:
  frontend:
    image: soliddesk/admin-frontend
    build: 
      context: .
      target: frontend
    volumes:
      - .:/var/www
  backend:
    image: soliddesk/backend
    build: 
      context: .
      target: backend
    volumes:
      - .:/var/www
      - /srv/share/composer-cache:/root/.composer/cache
      - /dev/null:/usr/local/etc/php/conf.d/opcache.ini
  app:
    image: soliddesk/app
    build: .
    volumes:
      - .:/var/www
      - /dev/null:/usr/local/etc/php/conf.d/opcache.ini
    ports:
      - 80:80
    depends_on:
      - database
  ci-test:
    image: soliddesk/app
    volumes:
      - ./vendor:/var/www/vendor
  database:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: soliddesk
